name: Intro to Github Actions

#When does this workflow run
on:
  push:

jobs:
    build-pnpm:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: pnpm/action-setup@v2
          with:
              version: 8

        - name: Install pnp
          run: pnpm install

        - name: Build
          run: pnpm run build

        - name: Run the server
          run: pnpm run preview &
            sleep 5

        - name: Curl the server
          run: curl -I http://localhost:4173